version: "3.7"

services:
  filebrowser:
    container_name: filebrowser-fixed
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}:/srv
      - ${APP_DATA_DIR}/database:/database
      - ${APP_DATA_DIR}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - FB_DATABASE=/database/filebrowser.db
      - FB_CONFIG=/config/settings.json
      - FB_ROOT=/srv
      - FB_LOG=stdout
      - FB_NOAUTH=false
      - FB_USERNAME=${FILEBROWSER_USERNAME}
      - FB_PASSWORD=${FILEBROWSER_PASSWORD}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser-fixed.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.filebrowser-fixed.entrypoints: websecure
      traefik.http.services.filebrowser-fixed.loadbalancer.server.port: 80
      runtipi.managed: true
    command: >
      sh -c "
      if [ ! -f /database/filebrowser.db ]; then
        /filebrowser config init --database /database/filebrowser.db;
        /filebrowser config set --address 0.0.0.0 --port 80 --database /database/filebrowser.db;
        /filebrowser users add ${FILEBROWSER_USERNAME} ${FILEBROWSER_PASSWORD} --perm.admin --database /database/filebrowser.db;
      fi;
      /filebrowser --database /database/filebrowser.db
      "

networks:
  tipi_main_network:
    external: true